import type { AgentDef, SlashCommand } from './interactive-types.js';

export const COMMANDS: SlashCommand[] = [
  { name: 'new', desc: 'New session (pick agent + objective)' },
  { name: 'attach', desc: 'Launch agent on active session' },
  { name: 'sessions', desc: 'List & manage sessions' },
  { name: 'active', desc: 'Current recording' },
  { name: 'watch', desc: 'Live event stream (tail -f style)' },
  { name: 'stats', desc: 'Session or global statistics' },
  { name: 'inspect', desc: 'Detailed session inspection' },
  { name: 'compare', desc: 'Compare sessions side by side' },
  { name: 'replay', desc: 'Replay a session (interactive)' },
  { name: 'export', desc: 'Export session as JSON' },
  { name: 'end', desc: 'End active sessions' },
  { name: 'restart', desc: 'Restart a session' },
  { name: 'approve', desc: 'Approve pending review gate actions' },
  { name: 'revert', desc: 'Revert file changes' },
  { name: 'delete', desc: 'Delete a session' },
  { name: 'purge', desc: 'Delete ALL sessions (including old)' },
  { name: 'kill', desc: 'Kill hawkeye background processes' },
  { name: 'settings', desc: 'Configure Hawkeye' },
  { name: 'tasks', desc: 'List & submit remote tasks' },
  { name: 'firewall', desc: 'Show recent interceptions & impact previews' },
  { name: 'analyze', desc: 'Root cause analysis — find why a session failed' },
  { name: 'memory', desc: 'Memory diff — what an agent remembers across sessions' },
  { name: 'autocorrect', desc: 'Autonomous control — auto-correct agent behavior' },
  { name: 'ci', desc: 'Post session report to GitHub PR (Check Run + comment)' },
  { name: 'swarm', desc: 'Multi-agent orchestration — list/show/init swarm runs' },
  { name: 'policy', desc: 'Manage security policies (init/check/show)' },
  { name: 'overnight', desc: 'Run overnight mode (guardrails + morning report)' },
  { name: 'report', desc: 'Generate morning report' },
  { name: 'remote', desc: 'Launch serve + daemon + tunnel (mobile access)' },
  { name: 'remote stop', desc: 'Stop tunnel + daemon' },
  { name: 'serve', desc: 'Open dashboard :4242' },
  { name: 'mcp', desc: 'Show MCP server setup instructions' },
  { name: 'init', desc: 'Initialize Hawkeye (auto-runs on /new)' },
  { name: 'clear', desc: 'Clear screen' },
  { name: 'quit', desc: 'Exit' },
].sort((left, right) => left.name.localeCompare(right.name));

export const AGENTS: AgentDef[] = [
  {
    name: 'Claude Code',
    command: 'claude',
    description: 'Anthropic Claude Code CLI',
    usesHooks: true,
  },
  {
    name: 'Cline',
    command: 'cline',
    description: 'Configurable multi-provider coding agent',
    needsInstall: 'npm install -g cline',
  },
  {
    name: 'Codex',
    command: 'codex',
    description: 'OpenAI Codex CLI',
    needsInstall: 'npm install -g @openai/codex',
  },
  { name: 'Custom command', command: '', description: 'Enter any command manually' },
].sort((left, right) => left.name.localeCompare(right.name));
